const COUNTRIES = [
  { code: "BE", name: "Belgium", language: "NL / FR / DE", email: "b2b-li", preferred: ["phone", "gbp", "form", "linkedin", "email"], note: "B2B legitimate interest is workable if you target a company address, identify yourself, and offer a one-click opt-out. Prefer Dutch in Flanders, French in Wallonia and Brussels." },
  { code: "NL", name: "Netherlands", language: "NL", email: "b2b-li", preferred: ["phone", "gbp", "form", "linkedin", "email"], note: "B2B email under legitimate interest is commonly used. Keep copy short and include an opt-out. Phone and GBP messages convert well with trades." },
  { code: "DE", name: "Germany", language: "DE", email: "opt-in", preferred: ["phone", "gbp", "form", "linkedin"], note: "UWG §7 is strict: unsolicited advertising email generally needs prior consent, including many B2B cases. Default to phone, GBP messages, website forms, or a warm intro." },
  { code: "FR", name: "France", language: "FR", email: "opt-in", preferred: ["phone", "form", "gbp", "linkedin"], note: "CNIL / LCEN lean opt-in for direct marketing. Do not scrape personal inboxes. Use the site form, phone, or a highly personalised LinkedIn note." },
  { code: "AT", name: "Austria", language: "DE", email: "opt-in", preferred: ["phone", "gbp", "form"], note: "Treat like Germany. Cold email is high-risk. Phone during opening hours and a mockup link via form or GBP is safer." },
  { code: "IT", name: "Italy", language: "IT", email: "opt-in", preferred: ["phone", "form", "gbp", "linkedin"], note: "Garante enforcement is strict on marketing. Prefer phone and contact forms." },
  { code: "ES", name: "Spain", language: "ES", email: "b2b-li", preferred: ["phone", "form", "email", "gbp"], note: "LSSI allows B2B email with easy opt-out. Document your source (public GBP) and never harvest consumer Gmail addresses." },
  { code: "PT", name: "Portugal", language: "PT", email: "b2b-li", preferred: ["phone", "form", "gbp", "email"], note: "B2B outreach is workable with identification + opt-out. Independent trades in Lisbon and Porto still answer the phone first." },
  { code: "IE", name: "Ireland", language: "EN", email: "b2b-li", preferred: ["phone", "email", "form", "linkedin"], note: "Corporate addresses + opt-out. Personal consumer emails need consent." },
  { code: "LU", name: "Luxembourg", language: "FR / DE / EN", email: "opt-in", preferred: ["phone", "linkedin", "form"], note: "Small market, high trust. Warm introductions and phone outperform volume email." },
  { code: "CH", name: "Switzerland", language: "DE / FR / IT", email: "opt-in", preferred: ["phone", "form", "linkedin"], note: "Not EU but nFADP + UWG-style rules. Be conservative. Phone and a live mockup win more than sequences." },
  { code: "DK", name: "Denmark", language: "DA", email: "opt-in", preferred: ["phone", "form", "gbp"], note: "Marketing Act is consent-heavy. Use phone and forms. Write in Danish for trades." },
  { code: "SE", name: "Sweden", language: "SV", email: "b2b-li", preferred: ["phone", "email", "linkedin", "form"], note: "B2B can work with transparency. Swedes expect plain language and a clear reason you looked them up." },
  { code: "PL", name: "Poland", language: "PL", email: "b2b-li", preferred: ["phone", "form", "email"], note: "B2B generally permitted with identification and opt-out. Local language is non-negotiable." },
  { code: "CZ", name: "Czechia", language: "CS", email: "b2b-li", preferred: ["phone", "form", "email"], note: "B2B email is used with opt-out. Phone still closes independent trades faster." },
];

const CITIES = [
  ["Antwerp", "BE", "Antwerpen"], ["Brussels", "BE", "Brussel"], ["Ghent", "BE", "Gent"], ["Bruges", "BE", "Brugge"], ["Liège", "BE", "Liège"], ["Leuven", "BE", "Leuven"],
  ["Amsterdam", "NL", "Amsterdam"], ["Rotterdam", "NL", "Rotterdam"], ["Utrecht", "NL", "Utrecht"], ["The Hague", "NL", "Den Haag"], ["Eindhoven", "NL", "Eindhoven"],
  ["Cologne", "DE", "Köln"], ["Düsseldorf", "DE", "Düsseldorf"], ["Munich", "DE", "München"], ["Hamburg", "DE", "Hamburg"], ["Frankfurt", "DE", "Frankfurt am Main"],
  ["Paris", "FR", "Paris"], ["Lyon", "FR", "Lyon"], ["Lille", "FR", "Lille"], ["Marseille", "FR", "Marseille"],
  ["Vienna", "AT", "Wien"], ["Milan", "IT", "Milano"], ["Rome", "IT", "Roma"], ["Madrid", "ES", "Madrid"], ["Barcelona", "ES", "Barcelona"],
  ["Lisbon", "PT", "Lisboa"], ["Porto", "PT", "Porto"], ["Dublin", "IE", "Dublin"], ["Luxembourg City", "LU", "Luxembourg"], ["Zurich", "CH", "Zürich"],
  ["Copenhagen", "DK", "København"], ["Stockholm", "SE", "Stockholm"], ["Warsaw", "PL", "Warszawa"], ["Prague", "CZ", "Praha"],
].map(([name, country, mapsQuery]) => ({ name, country, mapsQuery }));

const NICHES = [
  { id: "roofer", label: "Roofers / dakwerkers", search: { EN: "roofer", NL: "dakwerker", FR: "couvreur", DE: "Dachdecker", ES: "techador", IT: "coperturista", PT: "coberturas", DA: "taglægger", SV: "takläggare", PL: "dekarz", CS: "pokrývač" }, why: "High ticket, owners are on site not in Figma, and a weak Maps listing leaks storm-season jobs.", cpcLow: 1.2, cpcHigh: 4.0 },
  { id: "plumber", label: "Plumbers / loodgieters", search: { EN: "plumber", NL: "loodgieter", FR: "plombier", DE: "Klempner", ES: "fontanero", IT: "idraulico", PT: "canalizador", DA: "vvs", SV: "rörmokare", PL: "hydraulik", CS: "instalater" }, why: "Emergency intent is constant. A click-to-call GBP often beats a brochure website.", cpcLow: 1.5, cpcHigh: 5.0 },
  { id: "hvac", label: "HVAC / klimaat", search: { EN: "HVAC", NL: "airco installateur", FR: "climatisation", DE: "Heizung Sanitär", ES: "climatización", IT: "climatizzazione", PT: "climatização", DA: "vvs installatør", SV: "värmepump", PL: "klimatyzacja", CS: "topení" }, why: "Heat-pump subsidies across the EU created demand owners cannot digitally capture.", cpcLow: 1.4, cpcHigh: 4.5 },
  { id: "electrician", label: "Electricians", search: { EN: "electrician", NL: "elektricien", FR: "électricien", DE: "Elektriker", ES: "electricista", IT: "elettricista", PT: "eletricista", DA: "elektriker", SV: "elektriker", PL: "elektryk", CS: "elektrikář" }, why: "Charging points and panel upgrades are local, regulated work.", cpcLow: 1.2, cpcHigh: 4.5 },
  { id: "dentist", label: "Dentists / tandartsen", search: { EN: "dentist", NL: "tandarts", FR: "dentiste", DE: "Zahnarzt", ES: "dentista", IT: "dentista", PT: "dentista", DA: "tandlæge", SV: "tandläkare", PL: "dentysta", CS: "zubní lékař" }, why: "Trust category. Reviews + a clean booking path matter more than brand theatre.", cpcLow: 2.0, cpcHigh: 6.0 },
  { id: "salon", label: "Salons / barbers", search: { EN: "hair salon", NL: "kapsalon", FR: "salon de coiffure", DE: "Friseur", ES: "peluquería", IT: "parrucchiere", PT: "cabeleireiro", DA: "frisør", SV: "frisör", PL: "salon fryzjerski", CS: "kadeřnictví" }, why: "Independent salons live and die on Maps photos, hours, and tap-to-book.", cpcLow: 0.6, cpcHigh: 2.0 },
  { id: "law", label: "Local law firms", search: { EN: "lawyer", NL: "advocaat", FR: "avocat", DE: "Rechtsanwalt", ES: "abogado", IT: "avvocato", PT: "advogado", DA: "advokat", SV: "advokat", PL: "adwokat", CS: "advokát" }, why: "Avoid national networks. Solo kantoren with outdated sites still convert from Maps.", cpcLow: 4.0, cpcHigh: 8.0 },
  { id: "physio", label: "Physio / osteo", search: { EN: "physiotherapist", NL: "kinesist", FR: "kinésithérapeute", DE: "Physiotherapie", ES: "fisioterapeuta", IT: "fisioterapista", PT: "fisioterapeuta", DA: "fysioterapeut", SV: "sjukgymnast", PL: "fizjoterapeuta", CS: "fyzioterapeut" }, why: "Appointment businesses. A buried phone number on Maps is lost revenue every week.", cpcLow: 1.0, cpcHigh: 3.0 },
  { id: "garage", label: "Independent garages", search: { EN: "auto repair", NL: "garage", FR: "garage automobile", DE: "Autowerkstatt", ES: "taller mecánico", IT: "officina", PT: "oficina auto", DA: "autoværksted", SV: "bilverkstad", PL: "warsztat samochodowy", CS: "autoservis" }, why: "Skip dealer groups. Family garages with 4.2★ and 40 reviews are classic sweet-spot leads.", cpcLow: 1.0, cpcHigh: 3.0 },
  { id: "painter", label: "Painters / schilder", search: { EN: "painter decorator", NL: "schilder", FR: "peintre en bâtiment", DE: "Maler", ES: "pintor", IT: "imbianchino", PT: "pintor", DA: "maler", SV: "målare", PL: "malarz", CS: "malíř" }, why: "Visual trade. Before/after on a one-pager plus GBP photos beats a 2014 relic.", cpcLow: 1.0, cpcHigh: 2.8 },
];
